### ISSUE TITLE
Application does not write or even create output file

### ISSUE THREAD

**Issue by evolic** [mon/bigDecrypter#1]
Input file is processed, but nothing happens in the output directory.

P:>bigDecrypter.exe English.big p:\English.decrypted.big
Homeworld Remastered .big decrypter v1.4 by monty. http://github.com/mon/bigDecrypter
Opening English.big...
Performing sanity check...
Loading cipher...
0xDEADBE7A should be 266 bytes from file end
Found 0xDEADBE7A, located at byte 67627
Keysize detected: 256
Decrypting cipher...
Cipher loaded!
Decrypting 66kb from English.big into p:\English.decrypted.big...
[==============================================================================]

Decrypt success!

Please help!

**Comment by mon** [comment]
I've tried replicating this, I found that I could not write to my 2nd drive (E in my case), and I received an error when I tried. Not sure why fopen() returns a valid value in your case. Putting it into a subfolder on this drive worked, though I'm not entirely sure why.

Any luck with the drag and drop batch?

**Comment by evolic** [comment]
``` bash
Homeworld Remastered .big decrypter v1.4 by monty. http://github.com/mon/bigDecr
ypter
Opening C:\hw2\English.big...
Performing sanity check...
Loading cipher...
0xDEADBE7A should be 266 bytes from file end
Found 0xDEADBE7A, located at byte 67627
Keysize detected: 256
Decrypting cipher...
Cipher loaded!
Decrypting 66kb from C:\hw2\English.big into C:\hw2\English_decrypted.big...
[==============================================================================]

Decrypt success!
Aby kontynuować, naciśnij dowolny klawisz . . .
```

Still no luck :(

I will try to compile your app under Ubuntu.

**Comment by mon** [comment]
Just to rule out permissions issues, execute `echo "blah" > test.txt` in the data directory. Feels like a permissions issue :\

**Comment by mon** [comment]
Assumed to be fixed
